name: Auto Update
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the scraper
      run: python main.py
    - name: Commit results
      env:
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
      run: |
        set -e
        git config --global user.email "$COMMIT_EMAIL"
        git config --global user.name "$COMMIT_NAME"
        d="$(date --rfc-3339=s)"
        git add --all
        git commit --allow-empty -m "auto-update 📦 $d"
        git push origin main
