name: Manual Update
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the scraper
      run: python main.py
    - name: Commit results
      run: |
        set -e
        git config --global user.email "109694546+axois@users.noreply.github.com"
        git config --global user.name "axois"
        d="$(date --rfc-3339=s)"
        git add --all
        git commit --allow-empty -m "manual-update 📦 $d"
        git push origin main
    - name: Change to remote repo
      run: |
        git config --global user.email "109694546+axois@users.noreply.github.com"
        git config --global user.name "axois"
        git add --all
        git commit --allow-empty -m "manual-update 📦 $d"
        git remote add origin git@github.com:yemixzy/test.git
        git push -u origin main
